version: "3.7"
services:
  master:
    container_name: jenkins-master
    image: jenkins/jenkins:latest
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    - TZ=Europe/Zurich
    volumes:
    - /home/cbaer/work/private/jenkins-setup/jenkins-home:/var/jenkins_home/